name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install sshpass

    - name: Deploy to PythonAnywhere
      env:
        PA_PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
        PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        sshpass -p "$PA_PASSWORD" ssh -o "StrictHostKeyChecking=no" ${PA_USERNAME}@ssh.pythonanywhere.com << 'EOF'
          cd ~/myproject
          git pull origin main
          source virtualenv/bin/activate
          pip install -r requirements.txt
          exit
        EOF

    - name: Trigger PythonAnywhere Web App Restart
      run: |
        curl -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
          https://www.pythonanywhere.com/api/v1/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_APP_NAME }}/reload/