name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the deploy on

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      run: |
        sshpass -p ${{ secrets.PYTHONANYWHERE_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com << 'EOF'
          cd ~/myproject   # Navigate to your PythonAnywhere project directory
          git pull origin main  # Pull the latest changes from GitHub
          source virtualenv/bin/activate  # Activate virtual environment
          pip install -r requirements.txt  # Install any new dependencies
          exit
        EOF
        
    - name: Trigger PythonAnywhere Web App Restart
      run: |
        curl -u ${{ secrets.PYTHONANYWHERE_USERNAME }}:${{ secrets.PYTHONANYWHERE_API_TOKEN }} \
          https://www.pythonanywhere.com/api/v1/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_APP_NAME }}/reload/
